language: node_js
node_js:
  - "lts/*"
services:
 - postgresql
before_script:
 - psql -c "CREATE DATABASE potential;" -U postgres
 - psql -c "CREATE USER upotential WITH PASSWORD '1';" -U postgres


 
